[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
private_key = "${PRIVATE_KEY}"

[rpc_endpoints]
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${BASE_SEPOLIA_API_KEY}"

[etherscan]
base_sepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}" }